// react-hasura-app/src/components/photo-list/PhotoList.tsx
import {
  Box,
  Card,
  CardContent,
  CardHeader,
  CardMedia,
  Typography,
} from "@material-ui/core";
import React, { useState } from "react";
import { useParams } from "react-router-dom";
import { useGetUserPhotosQuery } from "../../generated/graphql";
import { PhotoDetailsDialog } from "../photo-details/PhotoDetailsDialog";

interface Props {}

export const PhotoList = (props: Props) => {
  const { id } = useParams<{ id: string }>();
  const [selectedPhotoId, setSelectedPhotoId] = useState("");
  const { data, loading } = useGetUserPhotosQuery({
    variables: { userId: id },
  });
  return (
    <div>
      {loading ? (
        <Typography variant="caption">Photos are being loaded...</Typography>
      ) : (
        <Box
          component="section"
          marginTop={4}
          display="grid"
          gridTemplateColumns="repeat(auto-fill, minmax(230px, 1fr))"
          gridGap="15px 15px"
        >
          {data?.photos.map(
            ({
              id,
              created_at,
              firebase_user_profile,
              photo_url,
              comments_aggregate,
            }) => (
              <Card key={id} onClick={() => setSelectedPhotoId(id)}>
                <CardHeader
                  title={"by: " + firebase_user_profile?.displayName}
                  subheader={new Intl.DateTimeFormat("en-US").format(
                    new Date(created_at)
                  )}
                />
                <CardMedia image={photo_url} style={{ paddingTop: "56.25%" }} />
                <CardContent>
                  <Typography variant="body2" color="textSecondary">
                    Comments: ({comments_aggregate.aggregate?.count})
                  </Typography>
                </CardContent>
              </Card>
            )
          )}
          <PhotoDetailsDialog
            photoId={selectedPhotoId}
            onCancel={() => setSelectedPhotoId("")}
            open={!!selectedPhotoId}
          />
        </Box>
      )}
    </div>
  );
};

// angular-hasura-app/src/app/features/photo-list/photo-list/photo-list.component.ts
import { PhotoDetailsDialogComponent } from './../../photo-details/photo-details-dialog/photo-details-dialog.component';
import { Observable } from 'rxjs';
import { GetUserPhotosGQL, GetUserPhotosQuery } from './../../../../generated/graphql';
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';
import { map, switchMap } from 'rxjs/operators';
import { MatDialog } from '@angular/material/dialog';

@Component({
  selector: 'app-photo-list',
  templateUrl: './photo-list.component.html',
  styleUrls: ['./photo-list.component.scss']
})
export class PhotoListComponent implements OnInit {

  photos$: Observable<GetUserPhotosQuery['photos']>;

  constructor(
    private getUserPhoto: GetUserPhotosGQL,
    private route: ActivatedRoute,
    private dialog: MatDialog) { }

  ngOnInit(): void {
    this.photos$ = this.route.params.pipe(
      switchMap(({ id }) => this.getUserPhoto.fetch({ userId: id })),
      map(({ data }) => data?.photos)
    );
  }

  onPhotoClick(photoId: string): void {
    this.dialog.open(PhotoDetailsDialogComponent, {
      data: { photoId }
    });
  }

}
<h2 class="mat-heading-1">Photos</h2>

<section *ngIf="photos$ | async as photos; else loading" class="list">
  <mat-card *ngFor="let photo of photos">
    <mat-card-header>
      <mat-card-title>by: {{ photo.firebase_user_profile.displayName }}</mat-card-title>
      <mat-card-subtitle>Published at: {{ photo.created_at | date: 'short' }}</mat-card-subtitle>
    </mat-card-header>
    <img mat-card-image (click)="onPhotoClick(photo.id)" [src]="photo.photo_url" class="image">
    <mat-card-actions>
      <span>Comments: ({{ photo.comments_aggregate.aggregate.count }})</span>
      <button mat-button>New Comment</button>
    </mat-card-actions>
  </mat-card>
</section>

<ng-template #loading>
  <div class="loading">Loading photos...</div>
</ng-template>
